# Generated by Django 5.2.2 on 2025-07-08 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='仪表盘名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='仪表盘描述')),
                ('layout', models.JSONField(default=dict, verbose_name='布局配置')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '仪表盘',
                'verbose_name_plural': '仪表盘',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='数据源名称')),
                ('type', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('csv', 'CSV文件'), ('api', 'API接口')], max_length=20, verbose_name='数据源类型')),
                ('connection_details', models.JSONField(verbose_name='连接信息')),
                ('description', models.TextField(blank=True, null=True, verbose_name='数据源描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否可用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '数据源',
                'verbose_name_plural': '数据源',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='图表名称')),
                ('type', models.CharField(choices=[('line', '折线图'), ('bar', '柱状图'), ('pie', '饼图'), ('scatter', '散点图'), ('area', '面积图'), ('radar', '雷达图'), ('gauge', '仪表盘'), ('funnel', '漏斗图')], max_length=20, verbose_name='图表类型')),
                ('config', models.JSONField(verbose_name='图表配置')),
                ('query', models.TextField(verbose_name='数据查询语句')),
                ('refresh_interval', models.PositiveIntegerField(default=0, verbose_name='刷新间隔(秒)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='图表描述')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='data_viz.datasource', verbose_name='数据源')),
            ],
            options={
                'verbose_name': '图表',
                'verbose_name_plural': '图表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.JSONField(verbose_name='位置信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_dashboards', to='data_viz.chart', verbose_name='图表')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_charts', to='data_viz.dashboard', verbose_name='仪表盘')),
            ],
            options={
                'verbose_name': '仪表盘图表',
                'verbose_name_plural': '仪表盘图表',
                'ordering': ['dashboard', 'chart'],
                'unique_together': {('dashboard', 'chart')},
            },
        ),
    ]
